apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helm-controller
  name: helm-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-controller
  template:
    metadata:
      labels:
        app: helm-controller
    spec:
      serviceAccountName: helm-controller
      containers:
        - command:
            - helm-controller
          image: rancher/helm-controller:v0.15.4
          name: helm-controller
          # admin service account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-controller
  namespace: kube-system
rules:
  - apiGroups: [ '*' ]
    resources: [ '*' ]
    verbs: [ '*' ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-controller
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helm-controller
subjects:
  - kind: ServiceAccount
    name: helm-controller
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: helm-controller
  namespace: kube-system
rules:
  - apiGroups: [ '*' ]
    resources: [ '*' ]
    verbs: [ '*' ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-controller
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: helm-controller
subjects:
  - kind: ServiceAccount
    name: helm-controller
    namespace: kube-system
