apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
spec:
  project: addons

  source:
    repoURL: "https://istio-release.storage.googleapis.com/charts"
    targetRevision: "1.21.1"
    chart: base

  destination:
    name: in-cluster
    namespace: istio-system

  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  project: addons

  source:
    repoURL: "https://istio-release.storage.googleapis.com/charts"
    targetRevision: "1.21.1"
    chart: istiod

  destination:
    name: in-cluster
    namespace: istio-system

  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway
  namespace: argocd
spec:
  project: addons

  source:
    repoURL: "https://istio-release.storage.googleapis.com/charts"
    targetRevision: "1.21.1"
    chart: gateway

  destination:
    name: in-cluster
    namespace: istio-system

  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
---
