apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: istio-base
  namespace: istio-system
spec:
  repo: https://istio-release.storage.googleapis.com/charts
  chart: base
  targetNamespace: istio-system
  valuesContent: |-
    defaultRevision: default
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: istiod
  namespace: istio-system
spec:
  repo: https://istio-release.storage.googleapis.com/charts
  chart: istiod
  targetNamespace: istio-system
---
