apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
spec:
  project: addons

  source:
    repoURL: "https://opensource.zalando.com/postgres-operator/charts"
    targetRevision: "1.4.0"
    chart: postgres-operator

  destination:
    name: in-cluster
    namespace: postgres-operator

  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator-ui
  namespace: argocd
spec:
  project: addons

  source:
    repoURL: "https://opensource.zalando.com/postgres-operator/charts"
    targetRevision: "1.4.0"
    chart: postgres-operator-ui

  destination:
    name: in-cluster
    namespace: postgres-operator

  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
---
