apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
  chart: postgres-operator
  targetNamespace: postgres-operator
  # valuesContent: |-
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: postgres-operator-ui
  namespace: postgres-operator
spec:
  repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
  chart: postgres-operator-ui
  targetNamespace: postgres-operator
  # valuesContent: |-
---
