apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password-connect
  namespace: argocd
spec:
  project: addons

  sources:
    - repoURL: "https://1password.github.io/connect-helm-charts"
      targetRevision: "1.15.1"
      chart: connect
      helm:
        valuesObject: {}

  destination:
    name: in-cluster
    namespace: 1password-connect

  syncPolicy:
    automated: null
