apiVersion: "acid.zalan.do/v1"
kind: "postgresql"

metadata:
  name: "mattermost-db"
  namespace: mattermost
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "15"
  numberOfInstances: 1
  volume:
    size: "50Gi"
    storageClass: "shared-path-protected"
  users:
    mmuser: []
  databases:
    mattermost: mmuser
  allowedSourceRanges:
    # IP ranges to access your cluster go here

  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      cpu: 500m
      memory: 1000Mi
