apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
spec:
  project: addons

  sources:
    - repoURL: "https://helm.releases.hashicorp.com"
      targetRevision: "0.5.2"
      chart: vault-secrets-operator
      helm:
        valueFiles:
          - $values/zen/sdlc/sigsrv-sdlc/root/k3s/addons/vault/vault-secret-operator-values.yaml
    - repoURL: 'git@github.com:sigsrv/infra.git'
      targetRevision: HEAD
      ref: values

  destination:
    name: in-cluster
    namespace: vault

  syncPolicy:
    automated: null
---
