apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: 1password-connect
  namespace: vault
spec:
  repo: https://1password.github.io/connect-helm-charts
  chart: connect
  targetNamespace: 1password
  valuesContent: |-
    connect:
      create: true
      credentialsName: op-credentials
      credentialsKey: 1password-credentials.json
    operator:
      create: true
      token:
        name: onepassword-token
        key: token
---
apiVersion: v1
kind: Namespace
metadata:
  name: 1password
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: onepassword-connector
  namespace: 1password
spec:
  vaultConnectionRef: vault/default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: 1password-onepassword-connector
    serviceAccount: onepassword-connector
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: onepassword-token
  namespace: 1password
spec:
  vaultAuthRef: onepassword-connector
  type: kv-v2
  mount: secret
  path: addon/1password/onepassword-token
  refreshAfter: 60s
  destination:
    create: true
    name: onepassword-token
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: op-credentials
  namespace: 1password
spec:
  vaultAuthRef: onepassword-connector
  type: kv-v2
  mount: secret
  path: addon/1password/op-credentials
  refreshAfter: 60s
  destination:
    create: true
    name: op-credentials
---
