#!/usr/bin/env just -f

help:
    @just --list

status:
    @tofu output -json | jq -r .status.value

apply:
    #!/usr/bin/env fish
    if test (just status) = "running"
        tofu apply
    else
        tofu apply -auto-approve -var status=ready
        tofu apply -auto-approve
    end

destory:
    tofu destroy
