#!/usr/bin/env just -f

help:
    @just --list

status:
    @tofu output -json | jq -r .cluster.value.config.status

apply:
    #!/usr/bin/env fish
    if test (just status) = "running"
        tofu apply
    else
        tofu apply -auto-approve -target module.cluster -var status=ready
        tofu apply -auto-approve -target module.cluster
        tofu apply -auto-approve
    end

destory:
    tofu destroy
