apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: matrix-synapse-cockroachdb
  namespace: synapse
spec:
  dataStore:
    pvc:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "10Gi"
        volumeMode: Filesystem
        storageClassName: "rook-ceph-fs-protected"
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  tlsEnabled: true
  image:
    name: cockroachdb/cockroach:v24.2.0
  nodes: 3

  affinity:
    podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - cockroachdb
