apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: addons

  sources:
    - repoURL: "https://helm.releases.hashicorp.com"
      targetRevision: "0.27.0"
      chart: vault
      helm:
        valuesObject:
          server:
            # logLevel: "debug"
            affinity: ""
            ha:
              enabled: true
              raft:
                enabled: true
                setNodeId: true
                config: |-
                  plugin_directory = "/usr/local/libexec/vault"
                  ui = true

                  listener "tcp" {
                    tls_disable = 1
                    address = "[::]:8200"
                    cluster_address = "[::]:8201"
                  }

                  storage "raft" {
                    path = "/vault/data"
                  }

                  service_registration "kubernetes" {}
            dataStorage:
              storageClass: local-path-protected
            auditStorage:
              storageClass: local-path-protected
            volumes:
              - name: plugins
                emptyDir: {}
            volumeMounts:
              - mountPath: /usr/local/libexec/vault
                name: plugins
                readOnly: true
            extraInitContainers:
              - name: vault-plugin-op-connect-init
                image: alpine:3
                command: [ "/bin/sh", "-c" ]
                args:
                  - |
                    set -euxo pipefail
                    wget https://github.com/1Password/vault-plugin-secrets-onepassword/releases/download/v${VAULT_PLUGIN_OP_CONNECT_VERSION}/vault-plugin-secrets-onepassword_${VAULT_PLUGIN_OP_CONNECT_VERSION}_${VAULT_PLUGIN_OP_CONNECT_ARCH}.zip -O /tmp/vault-plugin-secrets-onepassword.zip
                    unzip /tmp/vault-plugin-secrets-onepassword.zip -d /tmp
                    chmod +x /tmp/vault-plugin-secrets-onepassword_v${VAULT_PLUGIN_OP_CONNECT_VERSION}
                    mv /tmp/vault-plugin-secrets-onepassword_v${VAULT_PLUGIN_OP_CONNECT_VERSION} $VAULT_PLUGIN_DIR/op-connect
                env:
                  # https://github.com/1Password/vault-plugin-secrets-onepassword/releases
                  - name: VAULT_PLUGIN_OP_CONNECT_ARCH
                    value: "linux_amd64"
                  - name: VAULT_PLUGIN_OP_CONNECT_VERSION
                    value: "1.1.0"
                  - name: VAULT_PLUGIN_DIR
                    value: /usr/local/libexec/vault
                volumeMounts:
                  - name: plugins
                    mountPath: /usr/local/libexec/vault
          #  extraSecretEnvironmentVars:
          #  - envName: CONSUL_HTTP_TOKEN
          #    secretName: sigsrv-infra-microk8s-worker-consul-agent
          #    secretKey: CONSUL_HTTP_TOKEN

  destination:
    name: in-cluster
    namespace: vault

  syncPolicy:
    automated: null
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault
  namespace: vault
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault
                port:
                  number: 8200
  tls:
    - hosts:
        - vault-prod
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-active
  namespace: vault
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault-active
                port:
                  number: 8200
  tls:
    - hosts:
        - vault-active-prod
---
