apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: consul
  namespace: helm-charts
spec:
  repo: https://helm.releases.hashicorp.com
  chart: consul
  targetNamespace: vault
  # https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/values.yaml
  set:
    server.storageClass: cephfs-protected
  valuesContent: |-
    global:
      name: consul
    connectInject:
      enabled: false
      default: true
      namespaceSelector: |
        matchLabels:
          connect-inject : enabled
    server:
      replicas: 3
      bootstrapExpect: 3
    acls:
      manageSystemACLs: true
#    server:
#      extraConfig: |
#        {
#          "acl": {
#            "enabled": true,
#            "default_policy": "deny",
#            "down_policy": "extend-cache"
#          }
#        }
---
