apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: vault
  namespace: vault
spec:
  repo: https://helm.releases.hashicorp.com
  chart: vault
  targetNamespace: vault
  valuesContent: |-
    server:
      affinity: ""
      ha:
        enabled: true
        raft:
          enabled: true
        config: |-
          ui = true

          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }

          storage "consul" {
            path = "vault"
            address = "consul-server:8500"
          }
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: consul
  namespace: vault
spec:
  repo: https://helm.releases.hashicorp.com
  chart: consul
  targetNamespace: vault
  valuesContent: |-
    global:
      name: consul
    server:
      replicas: 3
      bootstrapExpect: 3
---
# TODO: https://developer.hashicorp.com/vault/tutorials/kubernetes/vault-secrets-operator
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: vault-secrets-operator
  namespace: vault
spec:
  repo: https://helm.releases.hashicorp.com
  chart: vault-secrets-operator
  targetNamespace: vault
  valuesContent: |-
    defaultVaultConnection:
      enabled: true
    
      address: "http://vault.vault.svc.cluster.local:8200"
      skipTLSVerify: false
      spec:
      template:
        spec:
          containers:
          - name: manager
            args:
            - "--client-cache-persistence-model=direct-encrypted"
