apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-app
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: matrix-synapse
            namespace: synapse
          - name: open-webui
            namespace: open-webui
  template:
    metadata:
      name: "apps-{{name}}"
      namespace: argocd
    spec:
      project: apps-app
      source:
        # path: "clusters/${cluster_env}/${cluster_alias}/apps/{{name}}"
        path: "clusters/prod/p1/apps/{{name}}"
        repoURL: "git@github.com:sigsrv/infra.git"
        targetRevision: HEAD
      destination:
        name: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        automated: null
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps-app
  namespace: argocd
spec:
  sourceRepos:
    - git@github.com:sigsrv/infra.git
  destinations:
    - name: in-cluster
      namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  sourceRepos:
    - git@github.com:sigsrv/infra.git
    - https://ananace.gitlab.io/charts
    - https://open-webui.github.io/helm-charts
  destinations:
    - name: in-cluster
      namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
