apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: addons

  sources:
    - repoURL: "https://helm.releases.hashicorp.com"
      targetRevision: "0.27.0"
      chart: vault
      helm:
        valueFiles:
          - $values/zen/prod/sigsrv-prod/root/k3s/addons/vault/vault-values.yaml
    - repoURL: 'git@github.com:sigsrv/infra.git'
      targetRevision: HEAD
      ref: values

  destination:
    name: in-cluster
    namespace: vault

  syncPolicy:
    automated: null
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault
  namespace: vault
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault
                port:
                  number: 8200
  tls:
    - hosts:
        - vault-prod
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-active
  namespace: vault
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault-active
                port:
                  number: 8200
  tls:
    - hosts:
        - vault-active-prod
---
