defaultVaultConnection:
  enabled: true

  address: "http://vault.vault.svc.cluster.local:8200"
  skipTLSVerify: false
  spec:
    template:
      spec:
        containers:
        - name: manager
          args:
          - "--client-cache-persistence-model=direct-encrypted"
