apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
spec:
  project: addons

  sources:
    - repoURL: "https://helm.releases.hashicorp.com"
      targetRevision: "0.5.2"
      chart: vault-secrets-operator
      helm:
        valuesObject:
          defaultVaultConnection:
            enabled: true

            address: "http://vault.vault.svc.cluster.local:8200"
            skipTLSVerify: false
            spec:
              template:
                spec:
                  containers:
                  - name: manager
                    args:
                    - "--client-cache-persistence-model=direct-encrypted"

  destination:
    name: in-cluster
    namespace: vault

  syncPolicy:
    automated: null
---
