config:
  core.https_address: '[::]:8443'
storage_pools:
- config:
    source: default
    volatile.initial_source: /dev/ubuntu-vg/ubuntu-data
    zfs.pool_name: default
  description: ""
  name: default
  driver: zfs
profiles:
- config: {}
  description: ""
  devices:
    root:
      path: /
      pool: default
      type: disk
  name: default
projects: []
cluster: null
