apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: addons

  source:
    repoURL: "https://charts.jetstack.io"
    targetRevision: "1.14.4"
    chart: cert-manager

  destination:
    name: in-cluster
    namespace: cert-manager

  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
