apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trust-manager
  namespace: argocd
spec:
  project: addons

  source:
    repoURL: "https://charts.jetstack.io"
    targetRevision: "0.9.2"
    chart: trust-manager

  destination:
    name: in-cluster
    namespace: cert-manager

  syncPolicy:
    automated: null
