apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-app
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: 1password-connect
            namespace: 1password-connect
          - name: cert-manager
            namespace: cert-manager
          - name: istio
            namespace: istio-system
          - name: local-path-protected
            namespace: kube-system
          - name: postgres-operator
            namespace: postgres-operator
          - name: registry
            namespace: container-registry
          - name: rook-ceph
            namespace: rook-ceph
          - name: tailscale-operator
            namespace: tailscale
          - name: vault
            namespace: vault
  template:
    metadata:
      name: "addon-{{name}}"
      namespace: argocd
    spec:
      project: addons-app

      source:
        path: "zen/sdlc/sigsrv-sdlc/cluster/addons/{{name}}"
        repoURL: 'git@github.com:sigsrv/infra.git'
        targetRevision: HEAD

      destination:
        name: in-cluster
        namespace: "{{namespace}}"

      syncPolicy:
        automated: null
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: addons-app
  namespace: argocd
spec:
  sourceRepos:
    - git@github.com:sigsrv/infra.git
  destinations:
    - name: in-cluster
      namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: addons
  namespace: argocd
spec:
  sourceRepos:
    - git@github.com:sigsrv/infra.git
    - https://1password.github.io/connect-helm-charts
    - https://charts.jetstack.io
    - https://charts.rook.io/release
    - https://helm.releases.hashicorp.com
    - https://istio-release.storage.googleapis.com/charts
    - https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    - https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
    - https://pkgs.tailscale.com/helmcharts
  destinations:
    - name: in-cluster
      namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
