apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: cluster-apps
            namespace: argocd
            path: "clusters/${cluster_env}/${cluster_alias}/apps"
  template:
    metadata:
      name: "{{name}}"
      namespace: argocd
    spec:
      project: cluster
      source:
        path: "{{path}}"
        repoURL: "git@github.com:sigsrv/infra.git"
        targetRevision: HEAD
      destination:
        name: in-cluster
        namespace: "{{namespace}}"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster
  namespace: argocd
spec:
  sourceRepos:
    - git@github.com:sigsrv/infra.git
  destinations:
    - name: in-cluster
      namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  namespace: argocd
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
  tls:
    - hosts:
        - argocd-${cluster_alias}
