apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-app
  namespace: argocd
spec:
  generators:
    - list:
        elements: []
  template:
    metadata:
      name: "apps-{{name}}"
      namespace: argocd
    spec:
      project: apps-app

      source:
        path: "zen/prod/sigsrv-prod/apps/{{name}}"
        repoURL: 'git@github.com:sigsrv/infra.git'
        targetRevision: HEAD

      destination:
        name: in-cluster
        namespace: "{{namespace}}"

      syncPolicy:
        automated: null
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps-app
  namespace: argocd
spec:
  sourceRepos:
    - git@github.com:sigsrv/infra.git
  destinations:
    - name: in-cluster
      namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  sourceRepos:
    - git@github.com:sigsrv/infra.git
  destinations:
    - name: in-cluster
      namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
