# incus admin init --dump
config:
  cluster.https_address: sigsrv.deer-neon.ts.net:8443
  core.https_address: sigsrv.deer-neon.ts.net:8443
  core.metrics_address: sigsrv.deer-neon.ts.net:8444
  user.ui_title: sigsrv
networks:
- config:
    ipv4.address: 10.100.0.1/16
    ipv4.nat: "true"
    ipv6.address: fd42:10:100::1/64
    ipv6.nat: "true"
  description: ""
  name: incusbr0
  type: bridge
  project: default
- config:
    ipv4.address: 10.95.162.1/24
    ipv4.nat: "true"
    ipv6.address: fd42:f029:4b0d:53fc::1/64
    ipv6.nat: "true"
  description: ""
  name: lxdbr0
  type: bridge
  project: default
- config:
    dns.domain: sigsrv-nas.lxd.local
    dns.search: 1.1.1.1,1.0.0.1
    ipv4.address: 10.40.96.1/24
    ipv4.nat: "true"
    ipv6.address: fdec:64:16::1/64
    ipv6.nat: "true"
  description: ""
  name: sigsrv-nas
  type: bridge
  project: default
- config:
    dns.domain: sigsrv-prod.lxd.local
    dns.search: 1.1.1.1,1.0.0.1
    ipv4.address: 10.64.0.1/16
    ipv4.nat: "true"
    ipv6.address: fdec:64::1/64
    ipv6.nat: "true"
  description: sigsrv-prod
  name: sigsrv-prod
  type: bridge
  project: default
- config:
    dns.domain: sigsrv-sdlc.lxd.local
    dns.search: 1.1.1.1,1.0.0.1
    ipv4.address: 10.128.0.1/16
    ipv4.nat: "true"
    ipv6.address: fdec:128::1/64
    ipv6.nat: "true"
  description: sigsrv-sdlc
  name: sigsrv-sdlc
  type: bridge
  project: default
- config:
    dns.domain: sigsrv-try.lxd.local
    dns.search: 1.1.1.1,1.0.0.1
    ipv4.address: 10.192.0.1/16
    ipv4.nat: "true"
    ipv6.address: fdec:192::1/64
    ipv6.nat: "true"
  description: sigsrv-try
  name: sigsrv-try
  type: bridge
  project: default
- config:
    dns.domain: talos-dev.lxd.local
    dns.search: 1.1.1.1,1.0.0.1
    ipv4.address: 10.32.0.1/16
    ipv4.nat: "true"
    ipv6.address: fdec:32::1/64
    ipv6.nat: "true"
  description: talos-dev
  name: talos-dev
  type: bridge
  project: default
- config:
    dns.domain: user.lxd.local
    dns.mode: managed
    dns.search: 1.1.1.1,1.0.0.1
    ipv4.address: 172.24.0.1/16
    ipv4.nat: "true"
    ipv6.address: none
  description: ""
  name: userbr0
  type: bridge
  project: default
storage_pools:
- config: {}
  description: ""
  name: hdd
  driver: zfs
- config: {}
  description: ""
  name: nvme
  driver: zfs
profiles:
- config:
    limits.cpu: "1"
    limits.memory: 2GiB
    migration.stateful: "true"
  description: Default Incus profile
  devices:
    eth0:
      network: userbr0
      type: nic
    root:
      path: /
      pool: nvme
      size: 20GiB
      type: disk
  name: default
projects:
- config:
    features.images: "true"
    features.networks: "false"
    features.networks.zones: "false"
    features.profiles: "true"
    features.storage.buckets: "true"
    features.storage.volumes: "true"
    limits.containers: "0"
    limits.cpu: "4"
    limits.disk: 1TiB
    limits.instances: "2"
    limits.memory: "17179869184"
    limits.networks: "1"
    limits.virtual-machines: "2"
    restricted: "false"
  description: user-chj
  name: chj
- config:
    features.images: "true"
    features.networks: "true"
    features.networks.zones: "true"
    features.profiles: "true"
    features.storage.buckets: "true"
    features.storage.volumes: "true"
    restricted: "false"
  description: Default Incus project
  name: default
- config:
    features.images: "true"
    features.profiles: "true"
    features.storage.buckets: "true"
    features.storage.volumes: "true"
    limits.containers: "0"
    limits.cpu: "4"
    limits.disk: 1TiB
    limits.instances: "2"
    limits.memory: "17179869184"
    limits.networks: "1"
    limits.virtual-machines: "2"
    restricted: "false"
  description: user-gldn2517
  name: gldn2517
- config:
    features.images: "true"
    features.networks: "false"
    features.networks.zones: "false"
    features.profiles: "true"
    features.storage.buckets: "true"
    features.storage.volumes: "true"
    limits.containers: "0"
    limits.disk: 1TiB
    limits.instances: "4"
    limits.memory: "34359738368"
    limits.networks: "2"
    limits.virtual-machines: "4"
    restricted: "false"
  description: user-jungooji
  name: jungooji
- config:
    features.images: "true"
    features.profiles: "true"
    features.storage.buckets: "true"
    features.storage.volumes: "true"
    limits.containers: "0"
    limits.cpu: "4"
    limits.disk: 1TiB
    limits.instances: "2"
    limits.memory: "17179869184"
    limits.networks: "1"
    limits.virtual-machines: "2"
    restricted: "false"
  description: user-kanta
  name: kanta
- config:
    features.images: "true"
    features.networks: "false"
    features.networks.zones: "false"
    features.profiles: "true"
    features.storage.buckets: "true"
    features.storage.volumes: "true"
    limits.containers: "0"
    limits.cpu: "6"
    limits.disk: 1TiB
    limits.instances: "2"
    limits.memory: "21474836480"
    limits.networks: "1"
    limits.virtual-machines: "2"
    restricted: "false"
  description: user-mms01276
  name: mms01276
- config:
    features.images: "true"
    features.networks: "false"
    features.networks.zones: "false"
    features.profiles: "true"
    features.storage.buckets: "true"
    features.storage.volumes: "true"
    limits.containers: "0"
    limits.disk: 4TiB
    limits.instances: "4"
    limits.memory: "68719476736"
    limits.networks: "2"
    limits.virtual-machines: "4"
    restricted: "false"
  description: user-myang2
  name: myang2
- config:
    features.images: "true"
    features.networks: "false"
    features.networks.zones: "false"
    features.profiles: "true"
    features.storage.buckets: "true"
    features.storage.volumes: "true"
    limits.containers: "0"
    limits.cpu: "8"
    limits.disk: 1TiB
    limits.instances: "2"
    limits.memory: "34359738368"
    limits.networks: "1"
    limits.virtual-machines: "2"
    restricted: "false"
  description: user-nyani
  name: nyani
- config:
    features.images: "true"
    features.networks: "false"
    features.networks.zones: "true"
    features.profiles: "true"
    features.storage.buckets: "true"
    features.storage.volumes: "true"
    limits.containers: "0"
    limits.cpu: "8"
    limits.disk: 16TiB
    limits.instances: "4"
    limits.memory: "17179869184"
    limits.networks: "1"
    limits.virtual-machines: "4"
    restricted: "false"
  description: sigsrv-nas
  name: sigsrv-nas
- config:
    features.images: "true"
    features.networks: "false"
    features.networks.zones: "true"
    features.profiles: "true"
    features.storage.buckets: "true"
    features.storage.volumes: "true"
    limits.containers: "16"
    limits.cpu: "32"
    limits.disk: 20TiB
    limits.instances: "32"
    limits.memory: 64GiB
    limits.networks: "4"
    limits.virtual-machines: "16"
  description: sigsrv-prod (managed by Terraform)
  name: sigsrv-prod
- config:
    features.images: "true"
    features.networks: "false"
    features.networks.zones: "true"
    features.profiles: "true"
    features.storage.buckets: "true"
    features.storage.volumes: "true"
    limits.containers: "16"
    limits.cpu: "32"
    limits.disk: 20TiB
    limits.instances: "32"
    limits.memory: 64GiB
    limits.networks: "4"
    limits.virtual-machines: "16"
  description: sigsrv-sdlc (managed by Terraform)
  name: sigsrv-sdlc
- config:
    features.images: "true"
    features.networks: "false"
    features.networks.zones: "true"
    features.profiles: "true"
    features.storage.buckets: "true"
    features.storage.volumes: "true"
    limits.containers: "16"
    limits.cpu: "32"
    limits.disk: 10TiB
    limits.instances: "32"
    limits.memory: 64GiB
    limits.networks: "4"
    limits.virtual-machines: "16"
  description: sigsrv-try (managed by Terraform)
  name: sigsrv-try
- config:
    features.images: "true"
    features.networks: "false"
    features.networks.zones: "true"
    features.profiles: "true"
    features.storage.buckets: "true"
    features.storage.volumes: "true"
    limits.containers: "16"
    limits.cpu: "32"
    limits.disk: 20TiB
    limits.instances: "32"
    limits.memory: 64GiB
    limits.networks: "4"
    limits.virtual-machines: "16"
  description: talos-dev (managed by Terraform)
  name: talos-dev
