apiVersion: v1
kind: Namespace
metadata:
  name: ceph-csi-cephfs
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ceph-csi-cephfs
  namespace: helm-charts
spec:
  repo: https://ceph.github.io/csi-charts
  chart: ceph-csi-cephfs
  targetNamespace: ceph-csi-cephfs
  valuesContent: |-
    csiConfig:
      - clusterID: ceph
        monitors:
        - v1:100.111.208.135:6789/0
---
