# https://github.com/ceph/ceph-csi/blob/devel/examples/cephfs/secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: default
stringData:
  # Required for statically provisioned volumes
  userID: myuser
  userKey: AQDZd0JlzMNqMBAAK1j7DShmJCLn5hEI3MIfvw==

  # Required for dynamically provisioned volumes
  adminID: myadmin
  adminKey: AQDjd0Jl4MMfMBAAnGfa3XbzDwJdl2eciEALQw==

  # Encryption passphrase
  encryptionPassphrase: test_passphrase
