# https://www.talos.dev/v1.9/kubernetes-guides/configuration/deploy-metrics-server/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
