apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operators-app
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: knative-operator
  template:
    metadata:
      name: "operator-{{name}}"
      namespace: argocd
    spec:
      project: operators-app

      source:
        path: "zen/sdlc/sigsrv-sdlc/cluster/operators/{{name}}"
        repoURL: 'git@github.com:sigsrv/infra.git'
        targetRevision: HEAD

      destination:
        name: in-cluster
        namespace: "{{namespace}}"

      syncPolicy:
        automated: null
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: operators-app
  namespace: argocd
spec:
  sourceRepos:
    - git@github.com:sigsrv/infra.git
  destinations:
    - name: in-cluster
      namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
