apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
spec:
  project: addons

  sources:
    - repoURL: "https://pkgs.tailscale.com/helmcharts"
      targetRevision: "1.62.1"
      chart: tailscale-operator
      helm:
        valuesObject:
          operatorConfig:
            hostname: sigsrv-sdlc-tailscale-operator
            defaultTags: {tag:sigsrv-sdlc-tailscale-operator}
          proxyConfig:
            defaultTags: tag:sigsrv-sdlc-tailscale-service
            apiServerProxyConfig:
                mode: true

  destination:
    name: in-cluster
    namespace: tailscale

  syncPolicy:
    automated: null
