apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-pvc
  namespace: mattermost-sdlc
spec:
  storageClassName: shared-path-protected
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
