apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openbao
  namespace: openbao
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openbao
                port:
                  number: 8200
  tls:
    - hosts:
        - openbao-${kubernetes.cluster.alias}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openbao-active
  namespace: openbao
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openbao-active
                port:
                  number: 8200
  tls:
    - hosts:
        - openbao-active-${kubernetes.cluster.alias}
