apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: external-dns
  namespace: helm-charts
spec:
  repo: https://kubernetes-sigs.github.io/external-dns/
  chart: external-dns
  targetNamespace: external-dns
  valuesContent: |-
    provider: cloudflare
    extraArgs:
      - --domain-filter=sigsrv.dev
      - --zone-id-filter=8bae321a816296c96dd3723a2b7e550e
      - --txt-owner-id=external-dns
      - --cloudflare-proxied
      - --cloudflare-dns-records-per-page=5000
    env:
    - name: CF_API_EMAIL
      value: "ecmaxp@ecmaxp.kr"
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-external-dns
          key: CF_API_TOKEN
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-external-dns
  namespace: external-dns
type: Opaque
data:
  CF_API_TOKEN: "ZVhYeVdXamdtMXRsRXZfc3c0MnpEZEZaWDZSd09RREpqZHZwM0lJXw=="
---
