apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rook-ceph
  namespace: helm-charts
spec:
  repo: https://charts.rook.io/release
  chart: rook-ceph
  targetNamespace: rook-ceph
  # https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/values.yaml
  valuesContent: |-
    csi:
      kubeletDirPath: /var/snap/microk8s/common/var/lib/kubelet
---
