apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: vault
  namespace: helm-charts
spec:
  repo: https://helm.releases.hashicorp.com
  chart: vault
  targetNamespace: vault
  set:
    server.dataStorage.storageClass: shared-path-protected
    server.auditStorage.storageClass: shared-path-protected
  # https://github.com/hashicorp/vault-helm/blob/main/values.yaml
  valuesContent: |-
    server:
      affinity: ""
      ha:
        enabled: true
        raft:
          enabled: true
          config: |-
            ui = true

            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }

            storage "consul" {
              address = "consul-server:8500"
              path = "vault/"
            }

            service_registration "kubernetes" {}
#      extraSecretEnvironmentVars:
#      - envName: CONSUL_HTTP_TOKEN
#        secretName: sigsrv-infra-microk8s-worker-consul-agent
#        secretKey: CONSUL_HTTP_TOKEN
---
# TODO: https://developer.hashicorp.com/vault/tutorials/kubernetes/vault-secrets-operator
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: vault-secrets-operator
  namespace: helm-charts
spec:
  repo: https://helm.releases.hashicorp.com
  chart: vault-secrets-operator
  targetNamespace: vault
  valuesContent: |-
    defaultVaultConnection:
      enabled: true
    
      address: "http://vault.vault.svc.cluster.local:8200"
      skipTLSVerify: false
      spec:
        template:
          spec:
            containers:
            - name: manager
              args:
              - "--client-cache-persistence-model=direct-encrypted"
---
