apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: sigsrv-k3s-1password-connect
  namespace: helm-charts
spec:
  repo: https://1password.github.io/connect-helm-charts
  chart: connect
  targetNamespace: 1password-sigsrv-k3s
  valuesContent: |-
    connect:
      create: true
      credentialsName: op-credentials
      credentialsKey: 1password-credentials.json
    operator:
      create: true
      token:
        name: onepassword-token
        key: token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: 1password-sigsrv-k3s
automountServiceAccountToken: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection
  namespace: 1password-sigsrv-k3s
spec:
  address: http://vault.vault.svc.cluster.local:8200
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: 1password-sigsrv-k3s
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: 1password-sigsrv-k3s-vault-auth
    serviceAccount: vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: onepassword-token
  namespace: 1password-sigsrv-k3s
spec:
  vaultAuthRef: vault-auth
  type: kv-v2
  mount: sigsrv-k3s/secret
  path: addons/1password/onepassword-token
  refreshAfter: 60s
  destination:
    create: true
    name: onepassword-token
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: op-credentials
  namespace: 1password-sigsrv-k3s
spec:
  vaultAuthRef: vault-auth
  type: kv-v2
  mount: sigsrv-k3s/secret
  path: addons/1password/op-credentials
  refreshAfter: 60s
  destination:
    create: true
    name: op-credentials
---
