apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  name: registry-claim
  namespace: container-registry
spec:
  storageClassName: cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
