apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative
spec:
  config:
    istio:
      local-gateways: |
        - name: knative-local-gateway
          namespace: knative
          service: knative-local-gateway.istio-system.svc.cluster.local
