apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs-volume
  namespace: seaweedfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seaweedfs-volume
  template:
    metadata:
      labels:
        app: seaweedfs-volume
    spec:
      containers:
        - name: seaweedfs-volume
          image: docker.io/chrislusf/seaweedfs:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 18080
              name: grpc
          command:
            - weed
            - volume
            - -dir=/data/volume
          volumeMounts:
            - mountPath: /data/volume
              name: data-volume
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: seaweedfs-volume-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-volume
  namespace: seaweedfs
spec:
  selector:
    app: seaweedfs-volume
  ports:
    - name: http
      port: 8080
    - name: grpc
      port: 18080
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seaweedfs-volume-pv
  namespace: seaweedfs
spec:
  storageClassName: local-path
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/ecmaxp/seaweedfs/volume
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-volume-pvc
  namespace: seaweedfs
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
---
